// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	Username  pgtype.Text
	Locale    string
	Bio       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UsersIdentityOidc struct {
	UserID pgtype.UUID
	Sub    string
}

type UsersIdentityTelegram struct {
	UserID     pgtype.UUID
	TelegramID int64
}
