volumes:
  dev_database:
    driver: local

networks:
  sisterra: ~

services:
  db:
    extends:
      file: compose.postgres.yml
      service: postgresql
    volumes:
      - dev_database:/var/lib/postgresql
    networks:
        - sisterra

  backend:
    restart: unless-stopped
    build:
      dockerfile: ./dev.Dockerfile
      context: .
    env_file: .env
    environment:
      APP_PG_ADDR: postgresql:5432
      APP_PG_DB: ${APP_PG_DB:-app}
      APP_PG_USER: ${APP_PG_USER:-app}
      APP_PG_PASS: ${APP_PG_PASS:?APP_PG_PASS required}
    ports:
      - 9090:9090
    volumes:
      - ./:/app
    networks:
      - auth-dev

  # TODO: Apply migrations container
