volumes:
  dev_database:
    driver: local
  dev_cache:
    driver: local

networks:
  dev: ~

services:
  db:
    extends:
      file: compose.infra.yml
      service: postgresql
    env_file: ./.env
    volumes:
      - dev_database:/var/lib/postgresql
    networks:
        - dev
    ports:
      - 5432:5432

  cache:
    extends:
      file: compose.infra.yml
      service: redis
    env_file: ./.env
    networks:
        - dev
    volumes:
      - dev_cache:/data

  backend:
    restart: unless-stopped
    build:
      dockerfile: ./dev.Dockerfile
      context: .
    env_file: .env
    environment:
      CACHE_URL: redis://:${REDIS_PASSWORD}@cache:6379
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9090:9090
    volumes:
      - ./:/app
    networks:
      - dev
