// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckUsernameAvailabilityOperation OperationName = "CheckUsernameAvailability"
	CreateUserOperation                OperationName = "CreateUser"
	DeleteMeOperation                  OperationName = "DeleteMe"
	GetMeOperation                     OperationName = "GetMe"
	GetUserByIDOperation               OperationName = "GetUserByID"
	GetUserByUsernameOperation         OperationName = "GetUserByUsername"
	UpdateMeOperation                  OperationName = "UpdateMe"
)
