// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *InternalErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Conflict represents sum type.
type Conflict struct {
	Type                     ConflictType // switch on this field
	ResourceConflictError    ResourceConflictError
	IdempotencyConflictError IdempotencyConflictError
}

// ConflictType is oneOf type of Conflict.
type ConflictType string

// Possible values for ConflictType.
const (
	ResourceConflictErrorConflict    ConflictType = "resource_exists"
	IdempotencyConflictErrorConflict ConflictType = "idempotency_conflict"
)

// IsResourceConflictError reports whether Conflict is ResourceConflictError.
func (s Conflict) IsResourceConflictError() bool { return s.Type == ResourceConflictErrorConflict }

// IsIdempotencyConflictError reports whether Conflict is IdempotencyConflictError.
func (s Conflict) IsIdempotencyConflictError() bool {
	return s.Type == IdempotencyConflictErrorConflict
}

// SetResourceConflictError sets Conflict to ResourceConflictError.
func (s *Conflict) SetResourceConflictError(v ResourceConflictError) {
	s.Type = ResourceConflictErrorConflict
	s.ResourceConflictError = v
}

// GetResourceConflictError returns ResourceConflictError and true boolean if Conflict is ResourceConflictError.
func (s Conflict) GetResourceConflictError() (v ResourceConflictError, ok bool) {
	if !s.IsResourceConflictError() {
		return v, false
	}
	return s.ResourceConflictError, true
}

// NewResourceConflictErrorConflict returns new Conflict from ResourceConflictError.
func NewResourceConflictErrorConflict(v ResourceConflictError) Conflict {
	var s Conflict
	s.SetResourceConflictError(v)
	return s
}

// SetIdempotencyConflictError sets Conflict to IdempotencyConflictError.
func (s *Conflict) SetIdempotencyConflictError(v IdempotencyConflictError) {
	s.Type = IdempotencyConflictErrorConflict
	s.IdempotencyConflictError = v
}

// GetIdempotencyConflictError returns IdempotencyConflictError and true boolean if Conflict is IdempotencyConflictError.
func (s Conflict) GetIdempotencyConflictError() (v IdempotencyConflictError, ok bool) {
	if !s.IsIdempotencyConflictError() {
		return v, false
	}
	return s.IdempotencyConflictError, true
}

// NewIdempotencyConflictErrorConflict returns new Conflict from IdempotencyConflictError.
func NewIdempotencyConflictErrorConflict(v IdempotencyConflictError) Conflict {
	var s Conflict
	s.SetIdempotencyConflictError(v)
	return s
}

func (*Conflict) createUserRes() {}
func (*Conflict) updateMeRes()   {}

// DeleteMeNoContent is response for DeleteMe operation.
type DeleteMeNoContent struct{}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code  OptString `json:"code"`
	Error string    `json:"error"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() OptString {
	return s.Code
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val OptString) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) checkUsernameAvailabilityRes() {}
func (*ErrorResponse) createUserRes()                {}
func (*ErrorResponse) getUserByIDRes()               {}
func (*ErrorResponse) getUserByUsernameRes()         {}
func (*ErrorResponse) updateMeRes()                  {}

// Merged schema.
// Ref: #/components/schemas/IdempotencyConflictError
type IdempotencyConflictError struct {
	// Merged property.
	Code  OptIdempotencyConflictErrorCode `json:"code"`
	Error string                          `json:"error"`
}

// GetCode returns the value of Code.
func (s *IdempotencyConflictError) GetCode() OptIdempotencyConflictErrorCode {
	return s.Code
}

// GetError returns the value of Error.
func (s *IdempotencyConflictError) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *IdempotencyConflictError) SetCode(val OptIdempotencyConflictErrorCode) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *IdempotencyConflictError) SetError(val string) {
	s.Error = val
}

// Merged schema.
type IdempotencyConflictErrorCode string

const (
	IdempotencyConflictErrorCodeIdempotencyConflict IdempotencyConflictErrorCode = "idempotency_conflict"
)

// AllValues returns all IdempotencyConflictErrorCode values.
func (IdempotencyConflictErrorCode) AllValues() []IdempotencyConflictErrorCode {
	return []IdempotencyConflictErrorCode{
		IdempotencyConflictErrorCodeIdempotencyConflict,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s IdempotencyConflictErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case IdempotencyConflictErrorCodeIdempotencyConflict:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *IdempotencyConflictErrorCode) UnmarshalText(data []byte) error {
	switch IdempotencyConflictErrorCode(data) {
	case IdempotencyConflictErrorCodeIdempotencyConflict:
		*s = IdempotencyConflictErrorCodeIdempotencyConflict
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// InternalErrorStatusCode wraps ErrorResponse with StatusCode.
type InternalErrorStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalErrorStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/NewUserRequest
type NewUserRequest struct {
	ID       UUID      `json:"id"`
	Username string    `json:"username"`
	Locale   string    `json:"locale"`
	Bio      OptString `json:"bio"`
}

// GetID returns the value of ID.
func (s *NewUserRequest) GetID() UUID {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *NewUserRequest) GetUsername() string {
	return s.Username
}

// GetLocale returns the value of Locale.
func (s *NewUserRequest) GetLocale() string {
	return s.Locale
}

// GetBio returns the value of Bio.
func (s *NewUserRequest) GetBio() OptString {
	return s.Bio
}

// SetID sets the value of ID.
func (s *NewUserRequest) SetID(val UUID) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *NewUserRequest) SetUsername(val string) {
	s.Username = val
}

// SetLocale sets the value of Locale.
func (s *NewUserRequest) SetLocale(val string) {
	s.Locale = val
}

// SetBio sets the value of Bio.
func (s *NewUserRequest) SetBio(val OptString) {
	s.Bio = val
}

// NewOptIdempotencyConflictErrorCode returns new OptIdempotencyConflictErrorCode with value set to v.
func NewOptIdempotencyConflictErrorCode(v IdempotencyConflictErrorCode) OptIdempotencyConflictErrorCode {
	return OptIdempotencyConflictErrorCode{
		Value: v,
		Set:   true,
	}
}

// OptIdempotencyConflictErrorCode is optional IdempotencyConflictErrorCode.
type OptIdempotencyConflictErrorCode struct {
	Value IdempotencyConflictErrorCode
	Set   bool
}

// IsSet returns true if OptIdempotencyConflictErrorCode was set.
func (o OptIdempotencyConflictErrorCode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptIdempotencyConflictErrorCode) Reset() {
	var v IdempotencyConflictErrorCode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptIdempotencyConflictErrorCode) SetTo(v IdempotencyConflictErrorCode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptIdempotencyConflictErrorCode) Get() (v IdempotencyConflictErrorCode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptIdempotencyConflictErrorCode) Or(d IdempotencyConflictErrorCode) IdempotencyConflictErrorCode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptResourceConflictErrorCode returns new OptResourceConflictErrorCode with value set to v.
func NewOptResourceConflictErrorCode(v ResourceConflictErrorCode) OptResourceConflictErrorCode {
	return OptResourceConflictErrorCode{
		Value: v,
		Set:   true,
	}
}

// OptResourceConflictErrorCode is optional ResourceConflictErrorCode.
type OptResourceConflictErrorCode struct {
	Value ResourceConflictErrorCode
	Set   bool
}

// IsSet returns true if OptResourceConflictErrorCode was set.
func (o OptResourceConflictErrorCode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResourceConflictErrorCode) Reset() {
	var v ResourceConflictErrorCode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResourceConflictErrorCode) SetTo(v ResourceConflictErrorCode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResourceConflictErrorCode) Get() (v ResourceConflictErrorCode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResourceConflictErrorCode) Or(d ResourceConflictErrorCode) ResourceConflictErrorCode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Merged schema.
// Ref: #/components/schemas/PrivUser
type PrivUser struct {
	ID        UUID      `json:"id"`
	Username  string    `json:"username"`
	Bio       string    `json:"bio"`
	Locale    string    `json:"locale"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *PrivUser) GetID() UUID {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *PrivUser) GetUsername() string {
	return s.Username
}

// GetBio returns the value of Bio.
func (s *PrivUser) GetBio() string {
	return s.Bio
}

// GetLocale returns the value of Locale.
func (s *PrivUser) GetLocale() string {
	return s.Locale
}

// GetCreatedAt returns the value of CreatedAt.
func (s *PrivUser) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *PrivUser) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *PrivUser) SetID(val UUID) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *PrivUser) SetUsername(val string) {
	s.Username = val
}

// SetBio sets the value of Bio.
func (s *PrivUser) SetBio(val string) {
	s.Bio = val
}

// SetLocale sets the value of Locale.
func (s *PrivUser) SetLocale(val string) {
	s.Locale = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *PrivUser) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *PrivUser) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*PrivUser) createUserRes() {}
func (*PrivUser) updateMeRes()   {}

// Ref: #/components/schemas/PubUser
type PubUser struct {
	ID       UUID   `json:"id"`
	Username string `json:"username"`
	Bio      string `json:"bio"`
}

// GetID returns the value of ID.
func (s *PubUser) GetID() UUID {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *PubUser) GetUsername() string {
	return s.Username
}

// GetBio returns the value of Bio.
func (s *PubUser) GetBio() string {
	return s.Bio
}

// SetID sets the value of ID.
func (s *PubUser) SetID(val UUID) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *PubUser) SetUsername(val string) {
	s.Username = val
}

// SetBio sets the value of Bio.
func (s *PubUser) SetBio(val string) {
	s.Bio = val
}

func (*PubUser) getUserByIDRes()       {}
func (*PubUser) getUserByUsernameRes() {}

// Merged schema.
// Ref: #/components/schemas/ResourceConflictError
type ResourceConflictError struct {
	// Merged property.
	Code  OptResourceConflictErrorCode `json:"code"`
	Error string                       `json:"error"`
}

// GetCode returns the value of Code.
func (s *ResourceConflictError) GetCode() OptResourceConflictErrorCode {
	return s.Code
}

// GetError returns the value of Error.
func (s *ResourceConflictError) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *ResourceConflictError) SetCode(val OptResourceConflictErrorCode) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ResourceConflictError) SetError(val string) {
	s.Error = val
}

// Merged schema.
type ResourceConflictErrorCode string

const (
	ResourceConflictErrorCodeResourceExists ResourceConflictErrorCode = "resource_exists"
)

// AllValues returns all ResourceConflictErrorCode values.
func (ResourceConflictErrorCode) AllValues() []ResourceConflictErrorCode {
	return []ResourceConflictErrorCode{
		ResourceConflictErrorCodeResourceExists,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceConflictErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ResourceConflictErrorCodeResourceExists:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceConflictErrorCode) UnmarshalText(data []byte) error {
	switch ResourceConflictErrorCode(data) {
	case ResourceConflictErrorCodeResourceExists:
		*s = ResourceConflictErrorCodeResourceExists
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SessionKey struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *SessionKey) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *SessionKey) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *SessionKey) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *SessionKey) SetRoles(val []string) {
	s.Roles = val
}

type TelegramMiniApp struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TelegramMiniApp) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TelegramMiniApp) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TelegramMiniApp) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TelegramMiniApp) SetRoles(val []string) {
	s.Roles = val
}

type TrustMeBro struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TrustMeBro) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TrustMeBro) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TrustMeBro) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TrustMeBro) SetRoles(val []string) {
	s.Roles = val
}

type UUID uuid.UUID

// Ref: #/components/schemas/UpdateUserRequest
type UpdateUserRequest struct {
	Username OptString `json:"username"`
	Locale   OptString `json:"locale"`
	Bio      OptString `json:"bio"`
}

// GetUsername returns the value of Username.
func (s *UpdateUserRequest) GetUsername() OptString {
	return s.Username
}

// GetLocale returns the value of Locale.
func (s *UpdateUserRequest) GetLocale() OptString {
	return s.Locale
}

// GetBio returns the value of Bio.
func (s *UpdateUserRequest) GetBio() OptString {
	return s.Bio
}

// SetUsername sets the value of Username.
func (s *UpdateUserRequest) SetUsername(val OptString) {
	s.Username = val
}

// SetLocale sets the value of Locale.
func (s *UpdateUserRequest) SetLocale(val OptString) {
	s.Locale = val
}

// SetBio sets the value of Bio.
func (s *UpdateUserRequest) SetBio(val OptString) {
	s.Bio = val
}

// Ref: #/components/schemas/UsernameAvailability
type UsernameAvailability struct {
	Available bool `json:"available"`
}

// GetAvailable returns the value of Available.
func (s *UsernameAvailability) GetAvailable() bool {
	return s.Available
}

// SetAvailable sets the value of Available.
func (s *UsernameAvailability) SetAvailable(val bool) {
	s.Available = val
}

func (*UsernameAvailability) checkUsernameAvailabilityRes() {}
