// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleSessionKey handles SessionKey security.
	// Session key issued by the authorization server after completing an
	// OIDC + PKCE flow with an external OAuth2 provider (e.g. Google, GitHub).
	// **Flow:**
	// 1. Client initiates PKCE: generates `code_verifier` + `code_challenge`
	// 2. Redirect to external provider's authorization endpoint
	// 3. Provider returns `authorization_code` to your callback URI
	// 4. Exchange `authorization_code` + `code_verifier` at `/auth/token`
	// 5. Server validates the OIDC `id_token`, creates a session, returns `session_key`
	// 6. Use the `session_key` as a Bearer token on protected endpoints
	// Format: `Authorization: Bearer <session_key>`.
	HandleSessionKey(ctx context.Context, operationName OperationName, t SessionKey) (context.Context, error)
	// HandleTelegramMiniApp handles TelegramMiniApp security.
	// Authenticates via Telegram Mini App using the signed `initData` string
	// provided by the Telegram WebApp JS SDK at launch.
	// The server validates the HMAC signature using the bot token secret.
	// Format: `Authorization: TMA <initData>`
	// Example: `Authorization: TMA query_id=AAF...&user=%7B...%7D&hash=abc123`
	// Reference: https://core.telegram.org/bots/webapps#validating-data-received-via-the-mini-app.
	HandleTelegramMiniApp(ctx context.Context, operationName OperationName, t TelegramMiniApp) (context.Context, error)
	// HandleTrustMeBro handles TrustMeBro security.
	// **Development/testing only. Never use in production.**
	// Authenticates as any user by providing their UUID directly — no credentials required.
	// Format: `Authorization: TMB <uuid>`
	// Example: `Authorization: TMB 550e8400-e29b-41d4-a716-446655440000`.
	HandleTrustMeBro(ctx context.Context, operationName OperationName, t TrustMeBro) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesSessionKey is a private map storing roles per operation.
var operationRolesSessionKey = map[string][]string{
	DeleteMeOperation:          []string{},
	GetMeOperation:             []string{},
	GetUserByIDOperation:       []string{},
	GetUserByUsernameOperation: []string{},
	UpdateMeOperation:          []string{},
}

// GetRolesForSessionKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSessionKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSessionKey(operation string) []string {
	roles, ok := operationRolesSessionKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesTelegramMiniApp is a private map storing roles per operation.
var operationRolesTelegramMiniApp = map[string][]string{
	DeleteMeOperation:          []string{},
	GetMeOperation:             []string{},
	GetUserByIDOperation:       []string{},
	GetUserByUsernameOperation: []string{},
	UpdateMeOperation:          []string{},
}

// GetRolesForTelegramMiniApp returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTelegramMiniApp(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTelegramMiniApp(operation string) []string {
	roles, ok := operationRolesTelegramMiniApp[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesTrustMeBro is a private map storing roles per operation.
var operationRolesTrustMeBro = map[string][]string{
	DeleteMeOperation:          []string{},
	GetMeOperation:             []string{},
	GetUserByIDOperation:       []string{},
	GetUserByUsernameOperation: []string{},
	UpdateMeOperation:          []string{},
}

// GetRolesForTrustMeBro returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTrustMeBro(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTrustMeBro(operation string) []string {
	roles, ok := operationRolesTrustMeBro[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securitySessionKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t SessionKey
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesSessionKey[operationName]
	rctx, err := s.sec.HandleSessionKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityTelegramMiniApp(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TelegramMiniApp
	const parameterName = "Authorization"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTelegramMiniApp[operationName]
	rctx, err := s.sec.HandleTelegramMiniApp(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityTrustMeBro(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TrustMeBro
	const parameterName = "Authorization"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTrustMeBro[operationName]
	rctx, err := s.sec.HandleTrustMeBro(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// SessionKey provides SessionKey security value.
	// Session key issued by the authorization server after completing an
	// OIDC + PKCE flow with an external OAuth2 provider (e.g. Google, GitHub).
	// **Flow:**
	// 1. Client initiates PKCE: generates `code_verifier` + `code_challenge`
	// 2. Redirect to external provider's authorization endpoint
	// 3. Provider returns `authorization_code` to your callback URI
	// 4. Exchange `authorization_code` + `code_verifier` at `/auth/token`
	// 5. Server validates the OIDC `id_token`, creates a session, returns `session_key`
	// 6. Use the `session_key` as a Bearer token on protected endpoints
	// Format: `Authorization: Bearer <session_key>`.
	SessionKey(ctx context.Context, operationName OperationName) (SessionKey, error)
	// TelegramMiniApp provides TelegramMiniApp security value.
	// Authenticates via Telegram Mini App using the signed `initData` string
	// provided by the Telegram WebApp JS SDK at launch.
	// The server validates the HMAC signature using the bot token secret.
	// Format: `Authorization: TMA <initData>`
	// Example: `Authorization: TMA query_id=AAF...&user=%7B...%7D&hash=abc123`
	// Reference: https://core.telegram.org/bots/webapps#validating-data-received-via-the-mini-app.
	TelegramMiniApp(ctx context.Context, operationName OperationName) (TelegramMiniApp, error)
	// TrustMeBro provides TrustMeBro security value.
	// **Development/testing only. Never use in production.**
	// Authenticates as any user by providing their UUID directly — no credentials required.
	// Format: `Authorization: TMB <uuid>`
	// Example: `Authorization: TMB 550e8400-e29b-41d4-a716-446655440000`.
	TrustMeBro(ctx context.Context, operationName OperationName) (TrustMeBro, error)
}

func (s *Client) securitySessionKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.SessionKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"SessionKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityTelegramMiniApp(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TelegramMiniApp(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TelegramMiniApp\"")
	}
	req.Header.Set("Authorization", t.APIKey)
	return nil
}
func (s *Client) securityTrustMeBro(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TrustMeBro(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TrustMeBro\"")
	}
	req.Header.Set("Authorization", t.APIKey)
	return nil
}
