// Code generated by ogen, DO NOT EDIT.
package api

type CheckUsernameAvailabilityRes interface {
	checkUsernameAvailabilityRes()
}

type CreateUserRes interface {
	createUserRes()
}

type GetUserByIDRes interface {
	getUserByIDRes()
}

type GetUserByUsernameRes interface {
	getUserByUsernameRes()
}

type UpdateMeRes interface {
	updateMeRes()
}
