// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CheckUsernameAvailability implements checkUsernameAvailability operation.
	//
	// Check username availability.
	//
	// GET /users/username/{username}/availability
	CheckUsernameAvailability(ctx context.Context, params CheckUsernameAvailabilityParams) (CheckUsernameAvailabilityRes, error)
	// CreateUser implements createUser operation.
	//
	// Create a new user.
	//
	// POST /users
	CreateUser(ctx context.Context, req *NewUserRequest) (CreateUserRes, error)
	// DeleteMe implements deleteMe operation.
	//
	// Delete own account.
	//
	// DELETE /users/me
	DeleteMe(ctx context.Context) error
	// GetMe implements getMe operation.
	//
	// Get own private info.
	//
	// GET /users/me
	GetMe(ctx context.Context) (*PrivUser, error)
	// GetUserByID implements getUserByID operation.
	//
	// Get public user info by ID.
	//
	// GET /users/{userID}
	GetUserByID(ctx context.Context, params GetUserByIDParams) (GetUserByIDRes, error)
	// GetUserByUsername implements getUserByUsername operation.
	//
	// Get public user info by username.
	//
	// GET /users/username/{username}
	GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (GetUserByUsernameRes, error)
	// UpdateMe implements updateMe operation.
	//
	// Update own profile.
	//
	// PATCH /users/me
	UpdateMe(ctx context.Context, req *UpdateUserRequest) (UpdateMeRes, error)
	// NewError creates *InternalErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *InternalErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
