// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CheckUsernameAvailability implements checkUsernameAvailability operation.
//
// Check username availability.
//
// GET /users/username/{username}/availability
func (UnimplementedHandler) CheckUsernameAvailability(ctx context.Context, params CheckUsernameAvailabilityParams) (r CheckUsernameAvailabilityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Create a new user.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *NewUserRequest) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMe implements deleteMe operation.
//
// Delete own account.
//
// DELETE /users/me
func (UnimplementedHandler) DeleteMe(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Get own private info.
//
// GET /users/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r *PrivUser, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByID implements getUserByID operation.
//
// Get public user info by ID.
//
// GET /users/{userID}
func (UnimplementedHandler) GetUserByID(ctx context.Context, params GetUserByIDParams) (r GetUserByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByUsername implements getUserByUsername operation.
//
// Get public user info by username.
//
// GET /users/username/{username}
func (UnimplementedHandler) GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (r GetUserByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMe implements updateMe operation.
//
// Update own profile.
//
// PATCH /users/me
func (UnimplementedHandler) UpdateMe(ctx context.Context, req *UpdateUserRequest) (r UpdateMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *InternalErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *InternalErrorStatusCode) {
	r = new(InternalErrorStatusCode)
	return r
}
