// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionKeyScopes      = "SessionKey.Scopes"
	TelegramMiniAppScopes = "TelegramMiniApp.Scopes"
	TrustMeBroScopes      = "TrustMeBro.Scopes"
)

// Defines values for IdempotencyConflictErrorCode.
const (
	IdempotencyConflict IdempotencyConflictErrorCode = "idempotency_conflict"
)

// Valid indicates whether the value is a known member of the IdempotencyConflictErrorCode enum.
func (e IdempotencyConflictErrorCode) Valid() bool {
	switch e {
	case IdempotencyConflict:
		return true
	default:
		return false
	}
}

// Defines values for ResourceConflictErrorCode.
const (
	ResourceExists ResourceConflictErrorCode = "resource_exists"
)

// Valid indicates whether the value is a known member of the ResourceConflictErrorCode enum.
func (e ResourceConflictErrorCode) Valid() bool {
	switch e {
	case ResourceExists:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// IdempotencyConflictError defines model for IdempotencyConflictError.
type IdempotencyConflictError struct {
	Code  *IdempotencyConflictErrorCode `json:"code,omitempty"`
	Error string                        `json:"error"`
}

// IdempotencyConflictErrorCode defines model for IdempotencyConflictError.Code.
type IdempotencyConflictErrorCode string

// NewUserRequest defines model for NewUserRequest.
type NewUserRequest struct {
	Bio      *string `json:"bio,omitempty"`
	Id       UUID    `json:"id"`
	Locale   string  `json:"locale"`
	Username string  `json:"username"`
}

// PrivUser defines model for PrivUser.
type PrivUser struct {
	Bio       string    `json:"bio"`
	CreatedAt time.Time `json:"created_at"`
	Id        UUID      `json:"id"`
	Locale    string    `json:"locale"`
	UpdatedAt time.Time `json:"updated_at"`
	Username  string    `json:"username"`
}

// PubUser defines model for PubUser.
type PubUser struct {
	Bio      string `json:"bio"`
	Id       UUID   `json:"id"`
	Username string `json:"username"`
}

// ResourceConflictError defines model for ResourceConflictError.
type ResourceConflictError struct {
	Code  *ResourceConflictErrorCode `json:"code,omitempty"`
	Error string                     `json:"error"`
}

// ResourceConflictErrorCode defines model for ResourceConflictError.Code.
type ResourceConflictErrorCode string

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Bio      *string `json:"bio,omitempty"`
	Locale   *string `json:"locale,omitempty"`
	Username *string `json:"username,omitempty"`
}

// UsernameAvailability defines model for UsernameAvailability.
type UsernameAvailability struct {
	Available bool `json:"available"`
}

// UserID defines model for UserID.
type UserID = openapi_types.UUID

// Username defines model for Username.
type Username = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict struct {
	union json.RawMessage
}

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = NewUserRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateUserRequest

// AsResourceConflictError returns the union data inside the Conflict as a ResourceConflictError
func (t Conflict) AsResourceConflictError() (ResourceConflictError, error) {
	var body ResourceConflictError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceConflictError overwrites any union data inside the Conflict as the provided ResourceConflictError
func (t *Conflict) FromResourceConflictError(v ResourceConflictError) error {
	v.Code = "resource_exists"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceConflictError performs a merge with any union data inside the Conflict, using the provided ResourceConflictError
func (t *Conflict) MergeResourceConflictError(v ResourceConflictError) error {
	v.Code = "resource_exists"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIdempotencyConflictError returns the union data inside the Conflict as a IdempotencyConflictError
func (t Conflict) AsIdempotencyConflictError() (IdempotencyConflictError, error) {
	var body IdempotencyConflictError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIdempotencyConflictError overwrites any union data inside the Conflict as the provided IdempotencyConflictError
func (t *Conflict) FromIdempotencyConflictError(v IdempotencyConflictError) error {
	v.Code = "idempotency_conflict"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIdempotencyConflictError performs a merge with any union data inside the Conflict, using the provided IdempotencyConflictError
func (t *Conflict) MergeIdempotencyConflictError(v IdempotencyConflictError) error {
	v.Code = "idempotency_conflict"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Conflict) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"code"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Conflict) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "idempotency_conflict":
		return t.AsIdempotencyConflictError()
	case "resource_exists":
		return t.AsResourceConflictError()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Conflict) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Conflict) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
